matrix:
  include:
    - os: osx
      env: BUILD_NAME=macosx
      compiler: clang
      language: cpp
      osx_image: xcode8.2
    - os: osx
      env: BUILD_NAME=ios
      compiler: clang
      language: cpp
      osx_image: xcode8.2
    - os: linux
      env: BUILD_NAME=debian
      compiler: gcc
      language: cpp
      dist: trusty
    - os: linux
      env: BUILD_NAME=ubuntu
      compiler: gcc
      language: cpp
      dist: trusty
    - os: linux
      env: BUILD_NAME=raspberry_pi
      compiler: gcc
      language: cpp
      dist: trusty
    - env: BUILD_NAME=android
      language: android

      
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
#    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository


env:
  global:
  #encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "QrMC5xtPy61Y0L3HVQoPJJ0/oGHV/mGnLmS5VlL+dyKHlTzwuLeIbUOc6yv3GyREAAH4WJXULROvxzecaKI25l1ywGReQvOv3lQ0/MFsVIYhmdMYbfgY6T1TgkBMEIZS5TFe8UzIjga4kTbjnEPQERxz/yhecl5f3/2RMX6bzgG39m79yB7LtK5cJXmX9rc8913IkAfpey9rW4L4V8adJvAo1OBlYg+dDAj7KQ/4fNtn03dffwoGV3HBuBmICeKGTomIrEbW8gtA0NFkJ43QKBIcexc4MHTYxb0vJ+ZTPDZiFTVhGMQ3VafaidLzXL5jP+YUfV+64Dd88zeo3Qpv7DHWMzrJ7EHSwK0PkwD4rlKdsbY3a1fcc+QlfXAX6HNVTMpE+f+VOXw0FGWSzRkUTmj8rfkV2DL0bZOqroqYYcBsqQlO0bIzwxu3ZuiFfnO5CYXBVLxwnnrVtYzJVyzWJwgQ2AzoS0YMfJE6SrKVevYZUMcTn8H7h10i/1VyhQyx/koLDwd1pVv/6BWDFCLpAlrHrRy+/EebthG2pJhW2fxG0fU8hM0U7dXJSG7i5NMOlj/JtEegP/nvgQOAgFocjY+fC7NNM2tETArSIBbt5qchZTX+XC2/u8YB7LydhBmphL6SlIiIjq+C8jRT8oV/XijcBhDU1+zZ52+BPyFO4tI="
  - MYCI_GIT_USERNAME=igagis
  - USE_ANDROID_NDK_VERSION=15c
  - linuxDependencies="debhelper lintian pkg-config myci prorab prorab-extra doxygen libutki-dev"

before_install:
- if [ "$BUILD_NAME" == "macosx" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&
    
    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install myci prorab prorab-extra libutki;
  fi
- if [ "$BUILD_NAME" == "ios" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&
    
    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install myci &&
    
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$MYCI_GIT_USERNAME:$MYCI_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git;
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    echo "deb [arch=amd64] https://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq myci;
  fi
- if [ "$BUILD_NAME" == "debian" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab prorab-extra myci debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg1,dirmngr,build-essential stretch /srv/chroot/deb-amd64 http://httpredir.debian.org/debian &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /srv/chroot/deb-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    echo 'APT::Get { AllowUnauthenticated "1"; };' | sudo tee /srv/chroot/deb-amd64/etc/apt/apt.conf.d/80unauthenticate > /dev/null &&
    sudo chroot /srv/chroot/deb-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo chroot /srv/chroot/deb-amd64 ln -s /usr/bin/gpg1 /usr/bin/gpg;
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild myci prorab prorab-extra debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg,dirmngr,build-essential --components=main,universe xenial /srv/chroot/ubu-amd64 http://archive.ubuntu.com/ubuntu/ &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /srv/chroot/ubu-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/ubu-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq myci;
    sudo myci-make-raspberry-chroot.sh /srv/chroot/rasp-armhf &&
    echo "deb http://dl.bintray.com/igagis/rasp unstable main" | sudo tee /srv/chroot/rasp-armhf/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/rasp-armhf sed -i -e 's/jessie/testing/g' /etc/apt/sources.list &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y $linuxDependencies g++ &&
    sudo mkdir -p /srv/chroot/rasp-armhf/build &&
    sudo rsync -av $TRAVIS_BUILD_DIR/ /srv/chroot/rasp-armhf/build/;
  fi


before_script:
  # download and install android NDK
  - if [ "$BUILD_NAME" == "android" ]; then
      export TERM=dumb &&
      curl -L https://dl.google.com/android/repository/android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip -O &&
      unzip ./android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip > /dev/null &&
      rm android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip &&
      export ANDROID_NDK_HOME=`pwd`/android-ndk-r$USE_ANDROID_NDK_VERSION &&
      export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME" &&
      export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64" &&
      export PATH=$PATH:${ANDROID_NDK_HOME} &&
      env;
    fi

script:
- if [ "$BUILD_NAME" == "debian" ]; then
    myci-deb-prepare.sh &&
    sg sbuild -c "sbuild -n -A -d stretch-amd64-sbuild --run-lintian --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    myci-deb-prepare.sh &&
    sg sbuild -c "sbuild -n -A -d xenial-amd64-sbuild --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "macosx" ]; then
    make;
  fi
# need to reduce output from xcodebuild because log size on travis-ci is limited by 4Mb, use grep for errors and warnings
# Also, need to set pipefail to make pipe exit code nono-zero in case first command fails but second succeeds (because grep exits with 0 always)
- if [ "$BUILD_NAME" == "ios" ]; then
    xcodebuild -workspace ios/tests.xcworkspace -scheme tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
            | sed -e "s/export PATH=[^ ]*/export PATH=.../g"
            | sed -e "s/[^ ]*\/clang /clang /g"
            | sed -e "s/\(-[IWfFL]\)[^ ]*/% /g"
            | sed -e "s/-isystem [^ ]*/%/g"
            | sed -e "s/-include [^ ]*/%/g"
            | sed -e "s/-MF [^ ]*/%/g"
            | sed -e "s/--serialize-diagnostics [^ ]*/%/g"
            | sed -e "s/-o [^ ]*/%/g"
            | sed -e "s/-iquote [^ ]*/%/g"
            | sed -e "s/-isysroot [^ ]*/%/g";
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && myci-deb-prepare.sh" &&
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && dpkg-buildpackage -us -uc";
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.pom.in &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
  fi

before_deploy:
  - myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` travis_bintray_*.json.in

deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_deb.json
  user: igagis
  key:
    secure: "O+G/Mak4SwnlJW0+ty3zA3zTA1Ua2AT2O/zCH7Lfp+OuWeZ8ocbp6MnYHuSL7jpUc8INObrP9B3ZPQxT8bTGmN0BK+DaKnxPwqCU7Z65UtJGBWV2fgw0AYnUSe78pefzO2il0lD9sX1g10riilFApRQ8lHlnMJra/FKgZ6ohsMExHtCnFE9jdrVhEe/tY8Y5m0qySJVbVyVXwReQj441/WCeB2QsyEYu+WSx/dn4DCl2okweVrpkW3+kFn1yXQUjnZuvXkuZWc9qCYg1YIXihjoA4MGC4fVwTma6OkhDqlOCqJBEnMNBMfRI9JHaQQzg/z9jvt/k9DXeMIICbmAFnRauoXN1o7KtTRYUVc+iBP6Fd035FVhC/PBbWS4d5+QL7wvGk6j4InE2ybnG2ePF5NbDDWxDDd7l6nsshN5pWcSEWsdXf2J8X1FeHcSO16X5b+vZHiptpdLJld56ghkIGPfTNOv4wsocU6rH262XzDdUG7D/THRJDQyfCATV2aME82XVntyQlRbp9iTfBgWiccKGDkLNFl8vYhAxH1XbLV6lAOyT0ZVRhxtQroos03G8w04i4akw7ewk3YwlQx+WxmD6wmITSc1lNiFCDzps/kPMf2+02t6/pQl+coSjyWx8wRGq1Z+rrQCYNUCzu7v1N5z29knwY367Wniz9sYZR7c="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_ubu.json
  user: igagis
  key:
    secure: "O+G/Mak4SwnlJW0+ty3zA3zTA1Ua2AT2O/zCH7Lfp+OuWeZ8ocbp6MnYHuSL7jpUc8INObrP9B3ZPQxT8bTGmN0BK+DaKnxPwqCU7Z65UtJGBWV2fgw0AYnUSe78pefzO2il0lD9sX1g10riilFApRQ8lHlnMJra/FKgZ6ohsMExHtCnFE9jdrVhEe/tY8Y5m0qySJVbVyVXwReQj441/WCeB2QsyEYu+WSx/dn4DCl2okweVrpkW3+kFn1yXQUjnZuvXkuZWc9qCYg1YIXihjoA4MGC4fVwTma6OkhDqlOCqJBEnMNBMfRI9JHaQQzg/z9jvt/k9DXeMIICbmAFnRauoXN1o7KtTRYUVc+iBP6Fd035FVhC/PBbWS4d5+QL7wvGk6j4InE2ybnG2ePF5NbDDWxDDd7l6nsshN5pWcSEWsdXf2J8X1FeHcSO16X5b+vZHiptpdLJld56ghkIGPfTNOv4wsocU6rH262XzDdUG7D/THRJDQyfCATV2aME82XVntyQlRbp9iTfBgWiccKGDkLNFl8vYhAxH1XbLV6lAOyT0ZVRhxtQroos03G8w04i4akw7ewk3YwlQx+WxmD6wmITSc1lNiFCDzps/kPMf2+02t6/pQl+coSjyWx8wRGq1Z+rrQCYNUCzu7v1N5z29knwY367Wniz9sYZR7c="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_rasp.json
  user: igagis
  key:
    secure: "O+G/Mak4SwnlJW0+ty3zA3zTA1Ua2AT2O/zCH7Lfp+OuWeZ8ocbp6MnYHuSL7jpUc8INObrP9B3ZPQxT8bTGmN0BK+DaKnxPwqCU7Z65UtJGBWV2fgw0AYnUSe78pefzO2il0lD9sX1g10riilFApRQ8lHlnMJra/FKgZ6ohsMExHtCnFE9jdrVhEe/tY8Y5m0qySJVbVyVXwReQj441/WCeB2QsyEYu+WSx/dn4DCl2okweVrpkW3+kFn1yXQUjnZuvXkuZWc9qCYg1YIXihjoA4MGC4fVwTma6OkhDqlOCqJBEnMNBMfRI9JHaQQzg/z9jvt/k9DXeMIICbmAFnRauoXN1o7KtTRYUVc+iBP6Fd035FVhC/PBbWS4d5+QL7wvGk6j4InE2ybnG2ePF5NbDDWxDDd7l6nsshN5pWcSEWsdXf2J8X1FeHcSO16X5b+vZHiptpdLJld56ghkIGPfTNOv4wsocU6rH262XzDdUG7D/THRJDQyfCATV2aME82XVntyQlRbp9iTfBgWiccKGDkLNFl8vYhAxH1XbLV6lAOyT0ZVRhxtQroos03G8w04i4akw7ewk3YwlQx+WxmD6wmITSc1lNiFCDzps/kPMf2+02t6/pQl+coSjyWx8wRGq1Z+rrQCYNUCzu7v1N5z29knwY367Wniz9sYZR7c="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = android
  file: travis_bintray_android.json
  user: igagis
  key:
    secure: "O+G/Mak4SwnlJW0+ty3zA3zTA1Ua2AT2O/zCH7Lfp+OuWeZ8ocbp6MnYHuSL7jpUc8INObrP9B3ZPQxT8bTGmN0BK+DaKnxPwqCU7Z65UtJGBWV2fgw0AYnUSe78pefzO2il0lD9sX1g10riilFApRQ8lHlnMJra/FKgZ6ohsMExHtCnFE9jdrVhEe/tY8Y5m0qySJVbVyVXwReQj441/WCeB2QsyEYu+WSx/dn4DCl2okweVrpkW3+kFn1yXQUjnZuvXkuZWc9qCYg1YIXihjoA4MGC4fVwTma6OkhDqlOCqJBEnMNBMfRI9JHaQQzg/z9jvt/k9DXeMIICbmAFnRauoXN1o7KtTRYUVc+iBP6Fd035FVhC/PBbWS4d5+QL7wvGk6j4InE2ybnG2ePF5NbDDWxDDd7l6nsshN5pWcSEWsdXf2J8X1FeHcSO16X5b+vZHiptpdLJld56ghkIGPfTNOv4wsocU6rH262XzDdUG7D/THRJDQyfCATV2aME82XVntyQlRbp9iTfBgWiccKGDkLNFl8vYhAxH1XbLV6lAOyT0ZVRhxtQroos03G8w04i4akw7ewk3YwlQx+WxmD6wmITSc1lNiFCDzps/kPMf2+02t6/pQl+coSjyWx8wRGq1Z+rrQCYNUCzu7v1N5z29knwY367Wniz9sYZR7c="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $BUILD_NAME = macosx
- provider: script
  skip_cleanup: true
  script: rvm 2.3.3 do myci-deploy-cocoapods.sh -r igagis
  on:
    tags: true
    condition: $BUILD_NAME = ios
    